// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pav.Parcial2Rec.Infraestructura.Datos;

#nullable disable

namespace Pav.Parcial2Rec.Infraestructura.Datos.Migrations
{
    [DbContext(typeof(PavParcialRecContext))]
    partial class PavParcialRecContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pav.Parcial2Rec.Dominio.Entidades.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadComensales")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numero"));

                    b.Property<bool>("OpcionReserva")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Mesas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7d25bf9-1e1c-4492-b589-612f54842d61"),
                            CantidadComensales = 4,
                            Descripcion = "Mesa 1",
                            Estado = true,
                            Numero = 1,
                            OpcionReserva = true,
                            SectorId = new Guid("e7ab2920-1e39-46b6-a838-90b9a4f2f30f")
                        },
                        new
                        {
                            Id = new Guid("98a563b2-198c-489f-88d6-3ec80bb1ea35"),
                            CantidadComensales = 7,
                            Descripcion = "Mesa 2",
                            Estado = true,
                            Numero = 2,
                            OpcionReserva = true,
                            SectorId = new Guid("6d7c9c08-b139-48e4-b25d-521801a02bdb")
                        });
                });

            modelBuilder.Entity("Pav.Parcial2Rec.Dominio.Entidades.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sectores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7ab2920-1e39-46b6-a838-90b9a4f2f30f"),
                            Numero = 1
                        },
                        new
                        {
                            Id = new Guid("6d7c9c08-b139-48e4-b25d-521801a02bdb"),
                            Numero = 2
                        },
                        new
                        {
                            Id = new Guid("e8c4d2e3-da49-41c7-a42e-2c0a0c7cec4b"),
                            Numero = 3
                        },
                        new
                        {
                            Id = new Guid("2c400385-d618-4caa-a3bf-e6f318c83633"),
                            Numero = 4
                        });
                });

            modelBuilder.Entity("Pav.Parcial2Rec.Dominio.Entidades.Mesa", b =>
                {
                    b.HasOne("Pav.Parcial2Rec.Dominio.Entidades.Sector", null)
                        .WithMany("Mesas")
                        .HasForeignKey("SectorId");
                });

            modelBuilder.Entity("Pav.Parcial2Rec.Dominio.Entidades.Sector", b =>
                {
                    b.Navigation("Mesas");
                });
#pragma warning restore 612, 618
        }
    }
}
